INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fashion', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Outdoors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Health', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Industrial', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Art', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Groceries', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cell Phones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Smart Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Wearable Tech', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Virtual Reality', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('3D Printing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fitness', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Yoga', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bikes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Skateboards', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Camping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fishing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hiking', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hunting', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Snow Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Water Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Travel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Luggage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Board Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Card Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Puzzles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Comics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Manga', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Anime', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('DIY', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Crafts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sewing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Knitting', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Painting', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drawing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Calligraphy', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Woodworking', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Metalworking', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Robotics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Programming', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('AI', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Machine Learning', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Data Science', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Math', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Physics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Chemistry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Biology', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Astronomy', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('History', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Philosophy', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Languages', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('English', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Spanish', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('French', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('German', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Chinese', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Japanese', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Korean', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Portuguese', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Arabic', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hebrew', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Russian', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ukrainian', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Coding', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Databases', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Networks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Security', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ethical Hacking', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Blockchain', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cryptocurrency', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Economics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Finance', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Investments', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Real Estate', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Law', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Politics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Psychology', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sociology', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Education', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Teaching', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('E-learning', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Careers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Entrepreneurship', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Startups', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Marketing', NOW());